language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c "create database palettepicker_test;" -U postgres
- npm run migrate
- npm run seed
test:
  adapter: postgresql
  database: palettepicker_test

deploy:
  provider: heroku
  api_key:
    secure: wcLr8U8fmNWg8XeBb78Z57M38/21Jo+WXEZrk6qU11VQ31ox5GcOnzLuY9Uvak7jEFMPlJxlkKtaRHASPcucwpkdwZMy4ajS8e13Nfbte1n3ldqGldO/p6bcRjVWeDwzTavurPtYszBagxE0FpYiTAqseUdUZbctPrOZjuL+J9Ik9qU/WUY2q0bflPkWjZWuNrlL26gVWVpqttb8z3KiNtDoUGprEaYkHKmUaysMhIFDQZ3hVal6t3KwOL5ZlaauzvFdPwL59pJyR/R9RTg1NqzLR7TwFAVYEFUNV3afViEHZ323tgve9u07eBbLYXLt7f4cbUBDwsvpPMZ7HlUB6jfRQbo8zMNib2TVaZro9sLgoUti+kfP7YyQPkwarXYEz31adrc93BYvXv5pPfQruHbUPXBsApDZ4DAioyZO4OH0Lz6KrpQqqcqylkb/aGMttxkywaYxqN3Sab0ztgc6Rdmrh4ZRMn0nYWcEYgAaBnRplS8AaKEo0ikK7iaoMXdzKFw17dhiXyaPbqT1X+l9OnLU9hH1d2bxMAaCb4oIxnWn/oa+zm87bHvTHhsjDoxyvSlmCRo8AbcD82Me2MrhxnWOHxIjkYxVTD3SA35u3DQzZ8WWPhpvgYjN+yVwDOguzxy723TuQyAKUdUoIdtof755DM3OPQJTweY03PTIB6Y=
  app: palette-picker-turing
  on: master