language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c "create database palettepicker_test;" -U postgres
- npm run migrate
- npm run seed
test:
  adapter: postgresql
  database: palettepicker_test

deploy:
  provider: heroku
  api_key:
    secure:   5d79144a-7b1b-4f9a-86a8-f927d7ea0189
  app: palette-picker-turing
  on: master

